#!/bin/sh

java -Dfile.encoding=UTF-8 -jar /usr/local/lib/tasm/Tasm7.jar $*

if [ $? -eq 0 ]; then
 n=$#
 src=`eval "echo \\$$n"`
 b=`expr $src : '\([^.]*\).t7'`

 echo
 echo "[${b}.lst]"
 cat ${b}.lst
fi
